.TH COLOR-CHRS.PL 1 "April 2016"
.SH NAME
color-chrs.pl \- Plot output of "bcftools +color-chrs"
.SH SYNOPSIS
.B color-chrs.pl
.RI [ OPTIONS ]
.I output.dat
.SH OPTIONS
.TP
.B \-c, \-\-colors \f[I]file
File with list of "chr hap color".
.TP
.B \-p, \-\-prefix \f[I]name
Prefix of output files
.TP
.B \-h, \-?, \-\-help
Summary of options.
.SH SEE ALSO
.BR bcftools (1)
