.TH PLOT-VCFSTATS 1 "November 2015"
.SH NAME
plot-vcfstats \- plot statistics for genomic variants in a VCF file
.SH DESCRIPTION
Call the program without any arguments for usage information.
This program requires bcftools' suggested packages in order to function.
See `apt-cache show bcftools` to see what the suggested packages are.
.SH SEE ALSO
.BR bcftools (1)
